//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailaddress { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> carYear { get; set; }
        public string carMake { get; set; }
        public string carModel { get; set; }
        public Nullable<bool> dui { get; set; }
        public Nullable<int> tickets { get; set; }
        public Nullable<bool> fullCoverage { get; set; }
        public Nullable<decimal> quotedPrice { get; set; }
    }
}
