//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceApprovalMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQuote
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> carYear { get; set; }
        public string carModel { get; set; }
        public string carMake { get; set; }
        public string DUI { get; set; }
        public Nullable<int> speedingTickets { get; set; }
        public string fullcoverage { get; set; }
    }
}
